application: flask-api-node
version: 1.1
runtime: python33
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/spi/.*
  script: api.api

libraries:
- name: pandas
  version: latest

- name: endpoints
  version: latest